# --- ОСНОВНЫЕ ПОРТЫ ---
port: 7890             # HTTP/HTTPS порт для ПК/клиентов
socks-port: 7891       # SOCKS5 порт
mixed-port: 1080       # Объединённый порт для редиректов
redir-port: 1182       # TProxy для LAN устройств
tproxy-port: 1181      # TProxy
allow-lan: true
mode: rule
log-level: silent
ipv6: false            # Можно включить true если сеть поддерживает
tcp-concurrent: true
unified-delay: true
geo-auto-update: true
geo-update-interval: 168
external-controller: 0.0.0.0:1995
secret: ""
external-ui: ./zash
external-ui-url: "https://github.com/Zephyruso/zashboard/releases/latest/download/dist-cdn-fonts.zip"
geodata-mode: true

# --- ПРОФИЛЬ ---
profile:
  store-selected: true
find-process-mode: "off"


# --- НАСТРОЙКИ СНИФФЕРА ---
sniffer:
  enable: true
  force-dns-mapping: true
  sniff:
    HTTP:
      ports: [80]
      override-destination: true
    TLS:
      ports: [443]
    QUIC:
      ports: [443]
      
# --- НАСТРОЙКИ DNS ---
dns:
  enable: true
  listen: 0.0.0.0:1053
  ipv6: false
  cache-algorithm: arc

  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16

  use-hosts: true
  respect-rules: true


  # Используем ЧИСТЫЕ IP
  proxy-server-nameserver:
    - 1.1.1.1
    - 8.8.8.8

  # Bootstrap DNS (ВСЕГДА IP)
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8

  # Основные DNS — ТОЛЬКО DoH
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://dns.google/dns-query

  # Точечные политики
  nameserver-policy:
    '+.supercell.net': https://dns.google/dns-query
    '+.brawlstarsgame.com': https://dns.google/dns-query

  fake-ip-filter-mode: blacklist
  fake-ip-filter:
    - '*.lan'
    - '*.local'
    - 'localhost'

    # Системные проверки
    - +.msftconnecttest.com
    - +.msftncsi.com
    - +.connectivitycheck.gstatic.com
    - +.detectportal.firefox.com

    # NTP
    - +.pool.ntp.org
    - +.ntp.org
    - +.time.windows.com

    # Мобильные сети
    - +.3gppnetwork.org

# --- ПРОВАЙДЕРЫ ПРОКСИ ---
proxy-providers:
  subscription:
    type: http
    url: ""            # <-- Подставляется автоматически при установке
    path: ./proxy-providers/subscription.yaml
    interval: 2160000
    health-check:
      enable: true
      url: http://www.msftncsi.com/ncsi.txt
      interval: 3000


# Прокси загружаются автоматически из подписки
proxies: []

# --- ГРУППЫ ПРОКСИ (ПОЛИТИКИ) ---
proxy-groups:

  - name: 'Gemini'
    type: select
    use:
      - subscription
    proxies:
      - DIRECT
    icon: "https://www.svgrepo.com/show/331406/gemini.svg"

  - name: 'Spotify'
    type: select
    use:
      - subscription
    proxies:
      - DIRECT
    icon: "https://www.svgrepo.com/show/349511/spotify.svg"
    
  - name: 'Discord'
    type: select
    use:
      - subscription
    proxies:
      - DIRECT
    icon: "https://www.svgrepo.com/show/331368/discord-v2.svg"
    
  - name: 'Whatsapp'
    type: select
    use:
      - subscription
    proxies:
      - DIRECT
    icon: "https://www.svgrepo.com/show/349511/spotify.svg"
    
    
  - name: 'Grok'
    type: select
    use:
      - subscription
    proxies:
      - DIRECT
    icon: "https://www.svgrepo.com/show/171491/compass.svg"

  - name: 'Netflix'
    type: select
    use:
      - subscription
    proxies:
      - DIRECT
    icon: "https://www.svgrepo.com/show/303341/netflix-1-logo.svg"
    
  - name: 'Fastly'
    type: select
    use:
      - subscription
    proxies:
      - DIRECT
    icon: "https://www.svgrepo.com/show/353730/fastly.svg"
    
  - name: 'Akamai'
    type: select
    use:
      - subscription
    proxies:
      - DIRECT
    icon: "https://www.svgrepo.com/show/353730/fastly.svg"
    
    
  - name: 'Viber'
    type: select
    use:
      - subscription
    proxies:
      - DIRECT
    icon: "https://www.svgrepo.com/show/125448/viber.svg"
    
  - name: 'Notion'
    type: select
    use:
      - subscription
    proxies:
      - DIRECT
    icon: "https://www.svgrepo.com/show/361558/notion-logo.svg"
    
  - name: 'Cloudflare'
    type: select
    use:
      - subscription
    proxies:
      - DIRECT
    icon: "https://www.svgrepo.com/show/349320/cloudflare.svg"

  - name: '2IP.IO'
    type: select
    use:
      - subscription
    proxies:
      - DIRECT
    icon: "https://www.svgrepo.com/show/502437/educate.svg"

  - name: 'Twitter'
    type: select
    use:
      - subscription
    proxies:
      - DIRECT
    icon: "https://www.svgrepo.com/show/452121/twitter-1.svg"
    
  - name: 'Apple'
    type: select
    use:
      - subscription
    proxies:
      - DIRECT
    icon: "https://www.svgrepo.com/show/494227/apple-rounded-border.svg"

  - name: 'Instagram'
    type: select
    use:
      - subscription
    proxies:
      - DIRECT
    icon: "https://www.svgrepo.com/show/452229/instagram-1.svg"
    
  - name: '18+'
    type: select
    use:
      - subscription
    proxies:
      - DIRECT
    icon: "https://www.svgrepo.com/show/530357/peach.svg"

  - name: 'Google'
    type: select
    use:
      - subscription
    proxies:
      - DIRECT
    icon: "https://www.svgrepo.com/show/475656/google-color.svg"
    
  - name: 'Google Play'
    type: select
    use:
      - subscription
    proxies:
      - DIRECT
    icon: "https://www.svgrepo.com/show/353828/google-play-icon.svg"
    
  - name: 'Twitch'
    type: select
    use:
      - subscription
    proxies:
      - DIRECT
    icon: "https://www.svgrepo.com/show/448251/twitch.svg"
    
  - name: 'TikTok'
    type: select
    use:
      - subscription
    proxies:
      - DIRECT
    icon: "https://www.svgrepo.com/show/349530/tiktok.svg"

  - name: 'Microsoft'
    type: select
    use:
      - subscription
    proxies:
      - DIRECT
    icon: "https://www.svgrepo.com/show/452062/microsoft.svg"

  - name: 'GitHub'
    type: select
    use:
      - subscription
    proxies:
      - DIRECT
    icon: "https://www.svgrepo.com/show/344880/github.svg"

  - name: 'Tidal'
    type: select
    use:
      - subscription
    proxies:
      - DIRECT
    icon: "https://www.svgrepo.com/show/504993/tidal.svg"
    
  - name: 'Roblox'
    type: select
    use:
      - subscription
    proxies:
      - DIRECT
    icon: "https://www.svgrepo.com/show/443377/brand-roblox.svg"
    
    
  - name: 'Telegram'
    type: select
    use:
      - subscription
    proxies:
      - DIRECT
    icon: "https://www.svgrepo.com/show/354443/telegram.svg"

  - name: 'Speedtest'
    type: select
    use:
      - subscription
    proxies:
      - DIRECT
    icon: "https://www.svgrepo.com/show/227645/speedometer.svg"

  - name: 'Linkedin'
    type: select
    use:
      - subscription
    proxies:
      - DIRECT
    icon: "https://www.svgrepo.com/show/448234/linkedin.svg"
    
    
  - name: 'Amazon'
    type: select
    use:
      - subscription
    proxies:
      - DIRECT
    icon: "https://www.svgrepo.com/show/475634/amazon-color.svg"
    
  - name: 'Facebook'
    type: select
    use:
      - subscription
    proxies:
      - DIRECT
    icon: "https://www.svgrepo.com/show/475647/facebook-color.svg"
    
  - name: 'other'
    type: select
    use:
      - subscription
    proxies:
      - DIRECT
    icon: "https://www.svgrepo.com/show/12922/growth.svg"

  - name: 'RU трафик'
    type: select
    use:
      - subscription
    proxies:
      - DIRECT
    icon: "https://www.svgrepo.com/show/508628/flag-ru.svg"

  - name: 'Остальной трафик'
    type: select
    exclude-filter: "(?i)Russia|RU"
    use:
      - subscription
    proxies:
      - DIRECT
    icon: "https://www.svgrepo.com/show/530294/branch.svg"

  - name: 'Блокировка рекламы'
    type: select
    use:
      - subscription
    proxies:
      - REJECT
      - DIRECT
    icon: "https://www.svgrepo.com/show/300290/sign-roadblock.svg"

  - name: 'YouTube'
    type: select
    use:
      - subscription
    proxies:
      - DIRECT
    icon: "https://www.svgrepo.com/show/13671/youtube.svg"

  - name: 'OpenAI'
    type: select
    use:
      - subscription
    proxies:
      - DIRECT
    icon: "https://www.svgrepo.com/show/306500/openai.svg"

  - name: 'Steam'
    type: select
    use:
      - subscription
    proxies:
      - DIRECT
    icon: "https://www.svgrepo.com/show/452107/steam.svg"

  - name: 'intel'
    type: select
    use:
      - subscription
    proxies:
      - DIRECT
    icon: "https://www.svgrepo.com/show/349412/intel.svg"

  - name: GLOBAL
    type: select
    hidden: true
    proxies:
      - 'YouTube'
      - 'Google'
      - 'Google Play'
      - 'Steam'
      - 'Microsoft'
      - 'GitHub'
      - 'Gemini'  
      - 'Instagram'
      - 'Linkedin'
      - 'Facebook'
      - 'Amazon'
      - 'Grok'
      - '18+'
      - 'Apple'
      - 'Telegram'
      - 'Roblox'
      - 'Fastly'
      - 'Cloudflare'
      - 'Viber'
      - 'Twitter'
      - 'intel' 
      - 'Notion' 
      - 'TikTok'
      - 'Speedtest'
      - 'Discord'
      - 'Twitch'
      - 'Whatsapp'
      - 'Netflix'
      - 'other'
      - 'Spotify'
      - 'OpenAI'
      - 'Tidal' 
      - 'RU трафик'
      - 'Блокировка рекламы'
      - 'Остальной трафик'
      - DIRECT

# --- НАСТРОЙКИ GEO-ДАННЫХ ---
geox-url:
  geosite: "https://github.com/v2fly/domain-list-community/releases/latest/download/dlc.dat"
  geoip: "https://github.com/MetaCubeX/meta-rules-dat/releases/latest/download/geoip.dat"

# --- ПРОВАЙДЕРЫ ПРАВИЛ ---
rule-providers:
  hagezi_pro:
    type: http
    behavior: domain
    format: mrs
    url: https://github.com/zxc-rv/ad-filter/releases/latest/download/adlist.mrs
    path: ./adblock/adlist.mrs
    interval: 86400

  discord:
    type: inline
    behavior: classical
    format: text
    payload:
      - AND,((DOMAIN-KEYWORD,discord),(NOT,((DOMAIN-SUFFIX,ru))))
      - AND,((IP-CIDR,34.0.192.0/18,no-resolve),(NETWORK,UDP),(DST-PORT,50000-50100))
      - AND,((IP-CIDR,35.192.0.0/11,no-resolve),(NETWORK,UDP),(DST-PORT,50000-50100))
      - AND,((IP-CIDR,66.22.192.0/18,no-resolve),(NETWORK,UDP),(DST-PORT,50000-50100))


# --- ПРАВИЛА МАРШРУТИЗАЦИИ ---
rules:
  # ПРАВИЛО №0: Блокировка рекламы и трекеров
  - GEOSITE,category-ads-all,Блокировка рекламы
#  - RULE-SET,hagezi_pro,Блокировка рекламы

  # ПРАВИЛО №1: Системные правила
  - GEOIP,private,DIRECT,no-resolve


  # ПРАВИЛО №2: Российский трафик
  - DOMAIN-SUFFIX,avito.ru,DIRECT
  - DOMAIN-SUFFIX,avito.st,DIRECT
  - GEOSITE,category-ru,RU трафик
  - DOMAIN-SUFFIX,ru,RU трафик
  - DOMAIN-SUFFIX,by,RU трафик
  - DOMAIN-SUFFIX,xn--p1ai,RU трафик
  - DOMAIN-SUFFIX,yandex-pogoda.static-storage.net,RU трафик
  - GEOSITE,category-gov-ru,RU трафик
  - GEOIP,RU,RU трафик,no-resolve
  

  # ПРАВИЛО №3: Правила для конкретных сервисов
  - OR,((DOMAIN-SUFFIX,gql.twitch.tv),(DOMAIN-SUFFIX,usher.ttvnw.net)),Twitch
  - GEOSITE,openai,OpenAI
  - RULE-SET,discord,Discord
  - GEOSITE,tidal,Tidal
  - GEOSITE,linkedin,Linkedin
  - GEOSITE,facebook,Facebook
  - GEOSITE,netflix,Netflix
  - GEOIP,netflix,Netflix
  - GEOSITE,spotify,Spotify
  - GEOSITE,speedtest,Speedtest
  - GEOSITE,ookla-speedtest,Speedtest
  - GEOSITE,category-speedtest,Speedtest 
  - GEOSITE,instagram,Instagram
  - GEOSITE,steam,Steam
  - IP-ASN,714,Apple
  - GEOSITE,apple,Apple
  - GEOSITE,youtube,YouTube
  - GEOSITE,twitter,Twitter
  - GEOSITE,tiktok,TikTok
  - GEOSITE,intel,intel
  - GEOSITE,notion,Notion
  - GEOSITE,google,Google
  - GEOSITE,google-play,Google Play
  - GEOSITE,google-gemini,Gemini
  - GEOSITE,github,GitHub
  - GEOSITE,microsoft,Microsoft
  - GEOSITE,telegram,Telegram
  - GEOIP,telegram,Telegram
  - DOMAIN-SUFFIX,grok.com,Grok
  
# CDN Fastly, Amazon
  - IP-ASN,16509,Amazon
  - GEOIP,fastly,Fastly


  
#  CDN Akamai
  - IP-ASN,12222,Akamai
  - IP-ASN,16625,Akamai
  - IP-ASN,16702,Akamai
  - IP-ASN,17204,Akamai
  - IP-ASN,17334,Akamai
  - IP-ASN,18680,Akamai
  - IP-ASN,18717,Akamai
  - IP-ASN,20189,Akamai
  - IP-ASN,20940,Akamai
  - IP-ASN,21342,Akamai
  - IP-ASN,22207,Akamai
  - IP-ASN,22452,Akamai
  - IP-ASN,23454,Akamai
  - IP-ASN,23455,Akamai
  - IP-ASN,23903,Akamai
  - IP-ASN,24319,Akamai
  - IP-ASN,26008,Akamai
  - IP-ASN,31107,Akamai
  - IP-ASN,31108,Akamai
  - IP-ASN,31109,Akamai
  - IP-ASN,31110,Akamai
  - IP-ASN,31377,Akamai
  - IP-ASN,32787,Akamai
  - IP-ASN,33905,Akamai
  - IP-ASN,34164,Akamai
  - IP-ASN,34850,Akamai
  - IP-ASN,35204,Akamai
  - IP-ASN,35993,Akamai
  - IP-ASN,35994,Akamai
  - IP-ASN,36183,Akamai
  
  
  # Roblox открыть порты xkeen -ap 80,443,49152:65535
  - AND,((IP-ASN,22697),(DST-PORT,49152-65535)),Roblox
  - GEOSITE,roblox,Roblox
  - DOMAIN-SUFFIX,roblox.com,Roblox
  - DOMAIN-SUFFIX,rbxcdn.com,Roblox
  - DOMAIN-SUFFIX,rbxinfra.net,Roblox
  
  # Viber
  - GEOSITE,viber,Viber
  - IP-ASN,16509,Viber
  
  
  # Whatsapp // открывам порты xkeen -ap 443,3478,46420
  - GEOSITE,whatsapp,Whatsapp
  - IP-ASN,32934,Whatsapp
  - IP-ASN,11917,Whatsapp
  - IP-ASN,9002,Whatsapp

  # SupperCell Открыть порт 9339 xkeen -ap 9339
  - GEOSITE,supercell,other
  - DOMAIN-KEYWORD,supercell,other
  - AND,((IP-ASN,14618),(DST-PORT,9339)),other
  - AND,((IP-ASN,16509),(DST-PORT,9339)),other

  # ПРАВИЛО №5: Проверка Ip адреса
  - DOMAIN-SUFFIX,2ip.io,2IP.IO
  - DOMAIN-SUFFIX,2ip.ru,2IP.IO
  - DOMAIN-SUFFIX,ipinfo.io,2IP.IO
  - DOMAIN-SUFFIX,ip-api.com,2IP.IO
  - DOMAIN-SUFFIX,whatismyipaddress.com,2IP.IO
  - DOMAIN-SUFFIX,whatismyip.com,2IP.IO
  - DOMAIN-SUFFIX,myip.com,2IP.IO
  - DOMAIN-SUFFIX,ipleak.net,2IP.IO
  - DOMAIN-SUFFIX,icanhazip.com,2IP.IO
  - DOMAIN-SUFFIX,ident.me,2IP.IO
  - DOMAIN-SUFFIX,ip.sb,2IP.IO
  - DOMAIN-SUFFIX,wimi5.com,2IP.IO
  - DOMAIN-SUFFIX,ip138.com,2IP.IO
  - DOMAIN-SUFFIX,ipify.org,2IP.IO
  - DOMAIN-SUFFIX,myexternalip.com,2IP.IO
  - DOMAIN-SUFFIX,trackip.net,2IP.IO


  # ПРАВИЛО №6: Необходимые сервисы с выбором
  - DOMAIN-SUFFIX,onlyfans.com,other
  - DOMAIN-SUFFIX,fansly.com,other
  - DOMAIN-SUFFIX,patreon.com,other
  - DOMAIN-SUFFIX,rockblack.su,other
  - DOMAIN-SUFFIX,rockblack.pro,other
  - DOMAIN-SUFFIX,rockblack.info,other
  
    # Торрент сайты
  - DOMAIN-SUFFIX,rutracker.org,other
  - DOMAIN-SUFFIX,rutor.info,other
  - DOMAIN-SUFFIX,lostfilm.tv,other
  - DOMAIN-SUFFIX,nnmclub.to,other
  - DOMAIN-SUFFIX,kinozal.tv,other
  - DOMAIN-SUFFIX,fast-torrent.ru,other
  - DOMAIN-SUFFIX,tapochek.net,other
  - DOMAIN-SUFFIX,rgfootball.net,other
  - DOMAIN-SUFFIX,thepiratebay.org,other
  - DOMAIN-SUFFIX,rarbg.to,other
  
  # ПРАВИЛО №7: Необходимые сервисы с выбором 18+
  - GEOSITE,category-porn,18+
  
  # kino.pub  
  - DOMAIN-SUFFIX,firebase-settings.crashlytics.com,other
  - DOMAIN-SUFFIX,firebaseinstallations.googleapis.com,other
  - DOMAIN-SUFFIX,kp-pro.cloud,other
  - DOMAIN-SUFFIX,firebaseremoteconfigrealtime.googleapis.com,other
  - DOMAIN-SUFFIX,firebaseremoteconfig.googleapis.com,other
  - DOMAIN-SUFFIX,cdn32.lol,other
  - DOMAIN-SUFFIX,kino.pub,other
  
  - IP-ASN,13335,Cloudflare
  
  # ПРАВИЛО №7: Весь остальной трафик
  - MATCH,Остальной трафик